version: '3.0'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

services:
  # сюда направляются запросы
  gate:
    container_name: gate
    build: gate
    ports:
      - 443:443
    networks:
      default:
        ipv4_address: 172.16.1.2

  # здесь хрнанятся данные
  center:
    container_name: center
    build: center
    ports:
      - 80:80
    networks:
      default:
        ipv4_address: 172.16.1.3
    volumes:
      - ./data:/data

  # сторонний dns сервер
  dns:
    container_name: dns
    restart: always
    build: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      default:
        ipv4_address: 172.16.1.9

  # внешние серверы
  node1:
    container_name: node1
    build: node
    ports:
      - 85:443
    networks:
      default:
        ipv4_address: 172.16.1.10
  node2:
    container_name: node2
    build: node
    ports:
      - 86:443
    networks:
      default:
        ipv4_address: 172.16.1.11
