version: '3.0'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

services:
  # сюда направляются запросы
  gate:
    container_name: gate
    build: gate
    ports:
      - ${PORT}:80
    networks:
      default:
        ipv4_address: 172.16.1.2

  # здесь хрнанятся данные
  center:
    container_name: center
    build: center
    ports:
      - :80
    networks:
      default:
        ipv4_address: 172.16.1.3

  # здесь определяется ip сервера для запроса
  dns:
    container_name: dns
    restart: always
    build: dns
    ports:
      - ":53/udp"
      - ":53/tcp"
    networks:
      default:
        ipv4_address: 172.16.1.5

  # внешние серверы
  node1:
    container_name: node1
    build: node
    networks:
      default:
        ipv4_address: 172.16.1.10
  node2:
    container_name: node2
    build: node
    ports:
      - 1000:80
    networks:
      default:
        ipv4_address: 172.16.1.11
